// screens/client/service_details_screen.dart
import 'package:flutter/material.dart';
import 'package:gemini_test/models/order.dart';
import 'package:gemini_test/models/service.dart';
import 'package:gemini_test/services/api_services.dart';
import 'package:provider/provider.dart';

class ServiceDetailsScreen extends StatelessWidget {
  final Service service;

  const ServiceDetailsScreen({super.key, required this.service});

  void _createOrder(BuildContext context) async {
    final apiService = Provider.of<ApiService>(context, listen: false);

    final order = Order(
      id: '', // Should be generated by backend
      status: 'pending',
      serviceName: '',
      pickupLocation: '',
      dropoffLocation: '',
    );

    try {
      final createdOrder = await apiService.createOrder(order);
      print('Order created successfully: $createdOrder');
      // Navigate to order confirmation or similar screen
    } catch (e) {
      print('Failed to create order: $e');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(service.name)),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(service.description, style: TextStyle(fontSize: 16)),
            SizedBox(height: 20),
            Text('Price: \$${service.price}', style: TextStyle(fontSize: 16)),
            SizedBox(height: 20),
            ElevatedButton(
              onPressed: () => _createOrder(context),
              child: Text('Order Service'),
            ),
          ],
        ),
      ),
    );
  }
}
